This is the error information for Dec_02_2015, created at Dec-02-2015 16:53:01:

Dec-02-2015 16:53:01 : HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /api/export (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10bb04250>: Failed to establish a new connection: [Errno 61] Connection refused',))
